---
- name: "Ubuntu20.04 - check Ubuntu20.04 package status"
  package:
    name:
      - net-tools
    state: "present"
  check_mode: yes
  register: pkg_status
 
- name: "Ubuntu20.04 - test Ubuntu20.04 package is installed"
  assert:
    that:
      - not pkg_status.changed