---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance-1
    image: docker.io/almalinux
    pre_build_image: true
  - name: instance-2
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: instance-3
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
