---

name: CI/CD
'on':
  pull_request:
  push:
    branches:
    - master

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos:8
          #- debian:latest
          - fedora:latest
          #- ubuntu:latest


    
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install test dependencies.
        run: pip3 install ansible molecule-docker docker yamllint ansible-lint
     
      # - name: Run ansible-lint with reviewdog
      #   uses: reviewdog/action-ansiblelint@v1.2

      - name: Run Molecule tests.
        run: |
          molecule --version
          
          tree
          molecule test      
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

